version: "3.8"  # optional since v1.27.0
services:
  web_api:
    build: 
      context: .
      dockerfile: .\Dls.Erp.Services.WebApi\Dockerfile
    container_name: web_api_application
    ports:
      - "8000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
  sql:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    container_name: sqlserver
    ports: # not actually needed, because the two services are on the same network
      - "1433:1433" 
    environment:
      - ACCEPT_EULA=y
      - SA_PASSWORD=Lem0nCode!